version: '3'

services:
  #php
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    links: 
      - db
      - redis
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "5555:80"
    networks:
      - app-network

  #Postgresql Service
  db:
    image: postgres:14
    container_name: db
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql
    ports:
      - "5556:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "5557:6379"
    networks:
      - app-network



#Docker Networks
networks:
  app-network:
    driver: bridge